export const INTERACTIVE_CONTENT = {
  zh: {
    navItems: [
      { id: 'home', label: '首頁' },
      { id: 'research', label: 'Research' },
      { id: 'teaching', label: 'Teaching' },
      { id: 'knowledge', label: 'Knowledge Lab' },
      { id: 'projects', label: 'Demo / MVP' },
      { id: 'contact', label: 'Collaboration' },
    ],
    common: {
      expand: '展開',
      collapse: '收合',
      openSubmenu: '展開子菜單',
      details: '詳細',
      externalLink: '外部連結',
      openDetails: '查看',
      close: '關閉',
      summaryLabel: '簡短說明',
      statusLabel: '目前狀態',
      nextActionLabel: '下一步行動',
      detailFallback: {
        status: '第一階段整備中',
        nextAction: '完成內容驗證後，進入第二階段實作。',
      },
    },
    submenus: {
      research: {
        title: 'Research Roadmap',
        description: '點擊 Research 後展開研究地圖子題，不在首頁一次鋪滿所有研究卡片。',
        items: ['AI Education', 'Personalized AI Tutoring', 'Learning Engagement / Satisfaction', 'AI Management / AI Business Education', 'NexAeon Research System'],
      },
      teaching: {
        title: 'Teaching Modules',
        description: '從校園痛點對應到可教、可練、可評估的 AI 課程能力。',
        items: ['Prompt Engineering', 'AI Research Workflow', 'Automation Workflow', 'AI Presentation / Report Design'],
      },
      knowledge: {
        title: 'Knowledge Lab Lifecycle',
        description: '資料從想法進入，經過自動化與 RAG，最後進入出版與實作輸出。',
        items: ['Idea Lab', 'Knowledge Intake', 'AI Tagging / Automation', 'RAG Knowledge Layer', 'MVP / Demo Lab', 'Publishing Hub'],
      },
      projects: {
        title: 'Demo / MVP Lab',
        description: '保留原型作為 Practice Proof，但首頁只呈現入口，細節由子菜單展開。',
        items: ['AI Tutoring MVP', 'Woosong Buddy', 'NexAeon Website', 'NexAeon Knowledge Hub'],
      },
      contact: {
        title: 'Collaboration Funnel',
        description: '依合作對象分流，讓第一次對話直接對準研究、課程、培訓或共創需求。',
        items: ['For Professors', 'For Universities', 'For Companies', 'For Students'],
      },
    },
    roleGuide: {
      eyebrow: 'Choose Your Role｜選擇你的身份入口',
      title: '五種身份，五個進入 NexAeon 的方式',
      subtitle: '這裡只作為入口導覽。選擇身份後，可以前往對應角色頁或先閱讀簡短定位。',
    },
    primaryModules: {
      eyebrow: 'Primary Navigation',
      title: '一級菜單核心介紹',
      subtitle: '首頁只呈現每個一級菜單的核心目的與入口，子內容會在點擊一級菜單後以子菜單方式展開。',
      cards: [
        {
          id: 'research',
          name: 'Research｜研究核心',
          position: '理論引擎',
          intro: 'NexAeon 的 Research 是理論引擎，用 AI Education、TAM、VARK、SRL、Learning Engagement 等理論，把教育問題轉化為可驗證的研究模型。它負責提出問題、建立框架與定義可被檢驗的證據路徑。',
          cta: '展開 Research Roadmap',
        },
        {
          id: 'teaching',
          name: 'Teaching｜教學設計',
          position: '從校園痛點出發的 AI 課程能力',
          intro: 'Teaching 將跨文化學生、AI 提問能力、可靠性判斷與成果轉化等問題，整理成可教學的課程模組。它讓學生不只會使用工具，也能把 AI 結果轉成作業、研究與展示成果。',
          cta: '展開 Teaching Modules',
        },
        {
          id: 'knowledge',
          name: 'Knowledge Lab｜第二大腦',
          position: '自我生長的知識系統',
          intro: 'Knowledge Lab 管理想法、資料、標籤、自動化與 RAG 知識層。它把零散資料沉澱成研究、課程、簡報、網站內容、Demo/MVP 與合作方案。',
          cta: '展開 Knowledge Lifecycle',
        },
        {
          id: 'projects',
          name: 'Demo / MVP｜實踐原型',
          position: 'Practice Proof',
          intro: 'Demo / MVP 是 NexAeon 將研究命題做成可展示、可測試、可迭代系統的證據。它不是一般作品集，而是研究落地與教學沙盒。',
          cta: '展開 Demo Lab',
        },
        {
          id: 'contact',
          name: 'Collaboration｜合作入口',
          position: '合作漏斗',
          intro: 'Collaboration 依教授、大學、企業與學生分流合作需求。它將共同研究、AI 課程、培訓、自動化與 MVP 共創導向合適的第一步。',
          cta: '展開 Collaboration Funnel',
        },
      ],
    },
    research: {
      eyebrow: 'Research Roadmap',
      title: 'Research Roadmap｜研究地圖',
      subtitle: '以 AI Education 為主軸，將理論模型、學習數據、研究系統與 Demo/MVP 實作串成可驗證的研究路徑。',
      roadmapLabel: 'Research Flow',
      theoryLabel: '底層理論基礎',
      projectsLabel: 'Research Projects｜研究落地原型',
      projectsDescription: 'Demo / MVP 不是普通作品展示，而是研究命題被轉成可測試、可蒐集回饋、可反覆迭代的實踐證據。',
      roadmap: [
        {
          title: 'AI Education',
          summary: '定義 AI 介入教學的場景、邊界與成效指標。',
          connects: ['Learning Engagement', 'Satisfaction / Adoption'],
        },
        {
          title: 'Personalized AI Tutoring',
          summary: '以學習者程度、節奏與任務目標設計個別化 AI 輔學策略。',
          connects: ['VARK', 'SRL'],
        },
        {
          title: 'Learning Engagement / Satisfaction',
          summary: '追蹤投入度、滿意度與採用意圖，驗證 AI 教育介入是否真正有效。',
          connects: ['Learning Engagement', 'TAM'],
        },
        {
          title: 'AI Management / AI Business Education',
          summary: '把 AI 工具導入課程、企業培訓與管理流程，形成可落地的教學與營運模型。',
          connects: ['TAM', 'Adoption'],
        },
        {
          title: 'NexAeon Research System',
          summary: '用 Knowledge Lab、RAG、Demo Lab 與 Publishing Hub 支撐研究持續生長。',
          connects: ['Research Workflow', 'Publishing'],
        },
      ],
      theories: [
        { title: 'TAM｜Technology Acceptance Model', summary: '解釋學習者與組織如何接受、採用並持續使用 AI 工具。' },
        { title: 'VARK｜Learning Styles', summary: '協助 AI Tutor 依視覺、聽覺、讀寫與動手型偏好調整回饋形式。' },
        { title: 'SRL｜Self-Regulated Learning', summary: '觀察目標設定、監控、反思與自我修正如何被 AI 工具支持。' },
        { title: 'Learning Engagement', summary: '把參與深度、互動品質與持續學習轉為可追蹤訊號。' },
        { title: 'Satisfaction / Adoption', summary: '衡量學習滿意度、信任感與長期採用意圖。' },
      ],
    },
    teaching: {
      eyebrow: 'Teaching Design',
      title: '從校園痛點出發的 AI 教學設計',
      subtitle: 'NexAeon 的教學不是工具展示，而是把真實學生問題轉化為可教、可練、可評估的 AI 能力。',
      painLabel: '校園痛點',
      solutionLabel: '課程模組 × 解法',
      sandboxLabel: 'Teaching Sandbox / Practice Output',
      painPoints: [
        '跨文化學生不知道如何向 AI 提問。',
        '學生不知道如何判斷 AI 回答是否可靠。',
        '學生不知道如何把 AI 結果轉化成作業、研究或實務成果。',
        '不同背景學生在 AI 工具使用能力上存在明顯差異。',
      ],
      modules: [
        { course: 'Prompt Engineering', solves: '解決不會提問的問題', output: '結構化問題、任務邊界、輸出格式與評估準則。' },
        { course: 'AI Research Workflow', solves: '解決文獻、問卷、資料分析與論文準備問題', output: '從研究問題到文獻摘要、問卷設計、資料整理與論文草稿。' },
        { course: 'Automation Workflow', solves: '解決重複行政與研究流程低效問題', output: '用 n8n / Notion / Airtable 思維設計可重複的工作流。' },
        { course: 'AI Presentation / Report Design', solves: '解決成果表達與學術展示問題', output: '把 AI 產出轉化為簡報、報告、海報與課堂展示。' },
      ],
      sandbox: 'Demo / MVP 作為學生理解 AI 教育工具與管理系統的實作沙盒：學生不只學 prompt，而是觀察一個教育工具如何被設計、測試、回饋與迭代。',
    },
    knowledge: {
      eyebrow: 'Knowledge Lab',
      title: 'Knowledge Lab｜第二大腦｜A Self-Growing Knowledge System',
      subtitle: '一筆資料從想法進入 NexAeon 後，會經過標籤、自動化整理、RAG 檢索增強與原型實驗，最後沉澱為研究、課程、簡報、網站內容、Demo/MVP 與合作方案。',
      lifecycleLabel: 'Knowledge Lifecycle',
      searchLabel: 'Knowledge Nodes',
      searchPlaceholder: '搜尋關鍵字（標題、摘要、分類、標籤）',
      noResults: '找不到符合條件的資料。',
      lifecycle: [
        'Idea Lab',
        'Knowledge Intake',
        'AI Tagging / Automation',
        'RAG Knowledge Layer',
        'MVP / Demo Lab',
        'Research / Teaching / Publishing',
        'Publishing Hub',
      ],
      lifecycleDetails: [
        '捕捉研究想法、課堂觀察、工具實驗與合作需求。',
        '匯入筆記、文獻、問卷、訪談、簡報與網站素材。',
        '由 AI 協助標籤、分類、摘要與任務分流。',
        '形成可檢索、可重組、可引用的知識增強層。',
        '把知識轉成可展示與可測試的 Demo / MVP。',
        '回流到論文、課程、出版、教案與管理流程。',
        '產出文章、網站頁面、簡報、合作提案與公開材料。',
      ],
    },
    projects: {
      eyebrow: 'Practice Proof',
      title: 'Demo Lab｜MVP 原型實驗室',
      subtitle: 'NexAeon 不是只有理念，而是已經把研究命題做成可展示、可測試、可迭代的原型系統。',
      cardLabels: {
        problem: 'Problem',
        aiLogic: 'AI Logic',
        useCase: 'Use Case',
        status: 'Status',
      },
    },
    contact: {
      eyebrow: 'Collaboration Funnel',
      title: 'Collaboration｜合作入口',
      description: '依不同合作對象分流研究、教學、AI 培訓、自動化與 MVP 共創需求，讓第一次對話就能對準問題。',
      email: 'AJ_Joey@nexaeon.studio',
      mailtoCta: '寄送 Email',
      copyCta: '複製 Email',
      copySuccessMessage: 'Email 已複製到剪貼簿。',
      copyFallbackMessage: '複製失敗，請手動複製上方 Email。',
      funnelLabel: '合作分流',
      formLabel: '輕量合作意向表單',
      submitLabel: '預留表單送出',
      formNote: '此區可替換為 Airtable Embed；目前先作為前台表單 UI 佔位。',
      fields: {
        name: 'Name',
        organization: 'Organization',
        role: 'Role',
        email: 'Email',
        collaborationType: 'Collaboration Type',
        message: 'Message',
      },
      types: [
        'Research Design',
        'AI Training',
        'Automation Workflow',
        'AI Education System',
        'Data / Survey Analysis',
        'Guest Lecture / Workshop',
        'MVP Prototype Co-development',
      ],
      funnels: [
        { title: 'For Professors', items: ['共同研究', '實驗設計', '問卷與數據分析'] },
        { title: 'For Universities', items: ['AI 課程設計', '學生 AI 能力培訓', '教育創新系統'] },
        { title: 'For Companies', items: ['AI 培訓', '自動化流程', 'ESG / HRM / SCM 分析'] },
        { title: 'For Students', items: ['AI 學習輔導', '研究訓練', '作品集建構'] },
      ],
    },
  },

  en: {
    navItems: [
      { id: 'home', label: 'Home' },
      { id: 'research', label: 'Research' },
      { id: 'teaching', label: 'Teaching' },
      { id: 'knowledge', label: 'Knowledge Lab' },
      { id: 'projects', label: 'Demo / MVP' },
      { id: 'contact', label: 'Collaboration' },
    ],
    common: {
      expand: 'Expand',
      collapse: 'Collapse',
      openSubmenu: 'Open Submenu',
      details: 'Details',
      externalLink: 'External Link',
      openDetails: 'Open',
      close: 'Close',
      summaryLabel: 'Summary',
      statusLabel: 'Current Status',
      nextActionLabel: 'Next Action',
      detailFallback: {
        status: 'In phase-one buildout',
        nextAction: 'Validate content quality, then move into phase-two implementation.',
      },
    },
    submenus: {
      research: {
        title: 'Research Roadmap',
        description: 'Research opens as a roadmap submenu instead of exposing every research card on the homepage.',
        items: ['AI Education', 'Personalized AI Tutoring', 'Learning Engagement / Satisfaction', 'AI Management / AI Business Education', 'NexAeon Research System'],
      },
      teaching: {
        title: 'Teaching Modules',
        description: 'Campus pain points are mapped into teachable, practiceable, assessable AI capabilities.',
        items: ['Prompt Engineering', 'AI Research Workflow', 'Automation Workflow', 'AI Presentation / Report Design'],
      },
      knowledge: {
        title: 'Knowledge Lab Lifecycle',
        description: 'Ideas move through intake, automation, RAG, prototypes, and publishing outputs.',
        items: ['Idea Lab', 'Knowledge Intake', 'AI Tagging / Automation', 'RAG Knowledge Layer', 'MVP / Demo Lab', 'Publishing Hub'],
      },
      projects: {
        title: 'Demo / MVP Lab',
        description: 'Prototypes remain Practice Proof, but homepage detail stays behind expandable navigation.',
        items: ['AI Tutoring MVP', 'Woosong Buddy', 'NexAeon Website', 'NexAeon Knowledge Hub'],
      },
      contact: {
        title: 'Collaboration Funnel',
        description: 'Collaboration is routed by audience so the first conversation starts from the right need.',
        items: ['For Professors', 'For Universities', 'For Companies', 'For Students'],
      },
    },
    roleGuide: {
      eyebrow: 'Choose Your Role',
      title: 'Five roles, five ways to enter NexAeon',
      subtitle: 'This is an entry guide only. Choose a role to open the relevant role page or read a compact positioning note.',
    },
    primaryModules: {
      eyebrow: 'Primary Navigation',
      title: 'Core Purpose of Each Top-Level Menu',
      subtitle: 'The homepage shows only each primary menu’s purpose and entry point. Child topics appear after clicking a top-level menu.',
      cards: [
        {
          id: 'research',
          name: 'Research',
          position: 'Theoretical engine',
          intro: 'NexAeon Research is the theoretical engine. It uses AI Education, TAM, VARK, SRL, and Learning Engagement to turn educational problems into verifiable research models and evidence paths.',
          cta: 'Open Research Roadmap',
        },
        {
          id: 'teaching',
          name: 'Teaching',
          position: 'AI course design from campus pain points',
          intro: 'Teaching translates cross-cultural learning issues, AI questioning, reliability judgment, and output transformation into course modules. Students learn how to turn AI outputs into assignments, research, and presentations.',
          cta: 'Open Teaching Modules',
        },
        {
          id: 'knowledge',
          name: 'Knowledge Lab',
          position: 'Self-growing second brain',
          intro: 'Knowledge Lab manages ideas, sources, tags, automation, and the RAG knowledge layer. It turns scattered material into research, courses, decks, website content, Demo/MVPs, and collaboration offers.',
          cta: 'Open Knowledge Lifecycle',
        },
        {
          id: 'projects',
          name: 'Demo / MVP',
          position: 'Practice Proof',
          intro: 'Demo / MVP proves that NexAeon has built visible, testable, iteratable systems from research questions. It is not a portfolio list; it is research landing and teaching sandbox evidence.',
          cta: 'Open Demo Lab',
        },
        {
          id: 'contact',
          name: 'Collaboration',
          position: 'Collaboration funnel',
          intro: 'Collaboration routes professors, universities, companies, and students toward the right first step. It connects joint research, AI curriculum, training, automation, and MVP co-development.',
          cta: 'Open Collaboration Funnel',
        },
      ],
    },
    research: {
      eyebrow: 'Research Roadmap',
      title: 'Research Roadmap',
      subtitle: 'AI Education is the main axis: theory, learning data, research systems, and Demo/MVP practice are connected into a verifiable research path.',
      roadmapLabel: 'Research Flow',
      theoryLabel: 'Theoretical Foundation',
      projectsLabel: 'Research Projects',
      projectsDescription: 'Demo / MVP work is not a portfolio display. It is practice evidence: research questions become testable systems that gather feedback and iterate.',
      roadmap: [
        {
          title: 'AI Education',
          summary: 'Defines where AI enters teaching, what boundaries matter, and how outcomes are evaluated.',
          connects: ['Learning Engagement', 'Satisfaction / Adoption'],
        },
        {
          title: 'Personalized AI Tutoring',
          summary: 'Designs adaptive tutoring strategies around learner level, rhythm, and task goals.',
          connects: ['VARK', 'SRL'],
        },
        {
          title: 'Learning Engagement / Satisfaction',
          summary: 'Tracks engagement, satisfaction, and adoption intention to validate whether AI intervention actually works.',
          connects: ['Learning Engagement', 'TAM'],
        },
        {
          title: 'AI Management / AI Business Education',
          summary: 'Deploys AI tools into courses, corporate training, and management workflows as practical teaching and operating models.',
          connects: ['TAM', 'Adoption'],
        },
        {
          title: 'NexAeon Research System',
          summary: 'Uses Knowledge Lab, RAG, Demo Lab, and Publishing Hub to keep research compounding.',
          connects: ['Research Workflow', 'Publishing'],
        },
      ],
      theories: [
        { title: 'TAM | Technology Acceptance Model', summary: 'Explains how learners and organizations accept, adopt, and continue using AI tools.' },
        { title: 'VARK | Learning Styles', summary: 'Helps AI tutors adapt feedback for visual, auditory, reading/writing, and kinesthetic preferences.' },
        { title: 'SRL | Self-Regulated Learning', summary: 'Examines how goal setting, monitoring, reflection, and self-correction can be supported by AI.' },
        { title: 'Learning Engagement', summary: 'Turns participation depth, interaction quality, and persistence into trackable signals.' },
        { title: 'Satisfaction / Adoption', summary: 'Measures learning satisfaction, trust, and long-term intention to adopt.' },
      ],
    },
    teaching: {
      eyebrow: 'Teaching Design',
      title: 'AI Teaching Design Starting From Campus Pain Points',
      subtitle: 'NexAeon teaching is not a tool demo. It turns real student problems into teachable, practiceable, assessable AI capabilities.',
      painLabel: 'Campus Pain Points',
      solutionLabel: 'Course Module × Capability',
      sandboxLabel: 'Teaching Sandbox / Practice Output',
      painPoints: [
        'Cross-cultural students do not know how to ask AI good questions.',
        'Students do not know how to judge whether AI answers are reliable.',
        'Students do not know how to turn AI outputs into assignments, research, or practical work.',
        'Students from different backgrounds show clear gaps in AI tool proficiency.',
      ],
      modules: [
        { course: 'Prompt Engineering', solves: 'Solves the problem of not knowing how to ask', output: 'Structured questions, task boundaries, output formats, and evaluation criteria.' },
        { course: 'AI Research Workflow', solves: 'Solves literature, survey, data analysis, and paper-preparation problems', output: 'From research questions to literature summaries, surveys, data structuring, and paper drafts.' },
        { course: 'Automation Workflow', solves: 'Solves inefficient repetitive administrative and research processes', output: 'Repeatable workflows designed through n8n / Notion / Airtable thinking.' },
        { course: 'AI Presentation / Report Design', solves: 'Solves academic expression and presentation problems', output: 'AI outputs become presentations, reports, posters, and classroom showcases.' },
      ],
      sandbox: 'Demo / MVP systems act as a practice sandbox for understanding AI education tools and management systems. Students do not only learn prompts; they observe how an education tool is designed, tested, reviewed, and iterated.',
    },
    knowledge: {
      eyebrow: 'Knowledge Lab',
      title: 'Knowledge Lab | Second Brain | A Self-Growing Knowledge System',
      subtitle: 'Once an item enters NexAeon, it moves through AI tagging, automation, RAG retrieval, and prototype experiments, then settles into research, courses, slides, web content, Demo/MVPs, and collaboration offers.',
      lifecycleLabel: 'Knowledge Lifecycle',
      searchLabel: 'Knowledge Nodes',
      searchPlaceholder: 'Search keywords (title, summary, category, tags)',
      noResults: 'No matching resources found.',
      lifecycle: [
        'Idea Lab',
        'Knowledge Intake',
        'AI Tagging / Automation',
        'RAG Knowledge Layer',
        'MVP / Demo Lab',
        'Research / Teaching / Publishing',
        'Publishing Hub',
      ],
      lifecycleDetails: [
        'Capture research ideas, classroom observations, tool experiments, and collaboration needs.',
        'Bring in notes, literature, surveys, interviews, slides, and site materials.',
        'Use AI to tag, classify, summarize, and route work.',
        'Build a searchable, reusable, citable knowledge layer.',
        'Turn knowledge into visible and testable Demo / MVP systems.',
        'Feed papers, courses, publishing, lesson design, and management workflows.',
        'Publish articles, website pages, decks, collaboration proposals, and public materials.',
      ],
    },
    projects: {
      eyebrow: 'Practice Proof',
      title: 'Demo Lab | MVP Prototype Laboratory',
      subtitle: 'NexAeon is not just an idea layer. Research questions have already become visible, testable, iteratable prototype systems.',
      cardLabels: {
        problem: 'Problem',
        aiLogic: 'AI Logic',
        useCase: 'Use Case',
        status: 'Status',
      },
    },
    contact: {
      eyebrow: 'Collaboration Funnel',
      title: 'Collaboration',
      description: 'Collaboration is routed by partner type so research, teaching, AI training, automation, and MVP co-development start with the right question.',
      email: 'AJ_Joey@nexaeon.studio',
      mailtoCta: 'Send Email',
      copyCta: 'Copy Email',
      copySuccessMessage: 'Email copied to clipboard.',
      copyFallbackMessage: 'Copy failed. Please copy the email manually.',
      funnelLabel: 'Collaboration Routing',
      formLabel: 'Lightweight Collaboration Intent Form',
      submitLabel: 'Reserved Submit',
      formNote: 'This area can be replaced with an Airtable Embed. For now it reserves the frontend form UI.',
      fields: {
        name: 'Name',
        organization: 'Organization',
        role: 'Role',
        email: 'Email',
        collaborationType: 'Collaboration Type',
        message: 'Message',
      },
      types: [
        'Research Design',
        'AI Training',
        'Automation Workflow',
        'AI Education System',
        'Data / Survey Analysis',
        'Guest Lecture / Workshop',
        'MVP Prototype Co-development',
      ],
      funnels: [
        { title: 'For Professors', items: ['Joint research', 'Experiment design', 'Survey and data analysis'] },
        { title: 'For Universities', items: ['AI curriculum design', 'Student AI capability training', 'Education innovation systems'] },
        { title: 'For Companies', items: ['AI training', 'Automation workflows', 'ESG / HRM / SCM analysis'] },
        { title: 'For Students', items: ['AI learning support', 'Research training', 'Portfolio building'] },
      ],
    },
  },

  ko: {
    navItems: [
      { id: 'home', label: '홈' },
      { id: 'research', label: 'Research' },
      { id: 'teaching', label: 'Teaching' },
      { id: 'knowledge', label: 'Knowledge Lab' },
      { id: 'projects', label: 'Demo / MVP' },
      { id: 'contact', label: 'Collaboration' },
    ],
    common: {
      expand: '열기',
      collapse: '닫기',
      openSubmenu: '하위 메뉴 열기',
      details: '상세',
      externalLink: '외부 링크',
      openDetails: '열기',
      close: '닫기',
      summaryLabel: '요약',
      statusLabel: '현재 상태',
      nextActionLabel: '다음 액션',
      detailFallback: {
        status: '1단계 구축 진행 중',
        nextAction: '콘텐츠 검증 후 2단계 구현으로 확장합니다.',
      },
    },
    submenus: {
      research: {
        title: 'Research Roadmap',
        description: 'Research를 클릭하면 연구 카드 전체가 홈에 펼쳐지는 대신 연구 지도 하위 메뉴가 열립니다.',
        items: ['AI Education', 'Personalized AI Tutoring', 'Learning Engagement / Satisfaction', 'AI Management / AI Business Education', 'NexAeon Research System'],
      },
      teaching: {
        title: 'Teaching Modules',
        description: '캠퍼스 문제를 가르치고 연습하고 평가할 수 있는 AI 역량으로 연결합니다.',
        items: ['Prompt Engineering', 'AI Research Workflow', 'Automation Workflow', 'AI Presentation / Report Design'],
      },
      knowledge: {
        title: 'Knowledge Lab Lifecycle',
        description: '아이디어가 수집, 자동화, RAG, 프로토타입, 출판 산출물로 이어지는 흐름입니다.',
        items: ['Idea Lab', 'Knowledge Intake', 'AI Tagging / Automation', 'RAG Knowledge Layer', 'MVP / Demo Lab', 'Publishing Hub'],
      },
      projects: {
        title: 'Demo / MVP Lab',
        description: '프로토타입은 Practice Proof로 유지하되, 상세 항목은 펼침 메뉴 안에서 보여줍니다.',
        items: ['AI Tutoring MVP', 'Woosong Buddy', 'NexAeon Website', 'NexAeon Knowledge Hub'],
      },
      contact: {
        title: 'Collaboration Funnel',
        description: '협력 대상을 기준으로 첫 대화를 적절한 요구와 연결합니다.',
        items: ['For Professors', 'For Universities', 'For Companies', 'For Students'],
      },
    },
    roleGuide: {
      eyebrow: 'Choose Your Role｜역할별 입구 선택',
      title: '다섯 역할, 다섯 개의 NexAeon 입구',
      subtitle: '이 모듈은 입구 안내만 담당합니다. 역할을 선택하면 해당 역할 페이지로 이동하거나 짧은 설명을 확인할 수 있습니다.',
    },
    primaryModules: {
      eyebrow: 'Primary Navigation',
      title: '1차 메뉴 핵심 소개',
      subtitle: '홈페이지는 각 1차 메뉴의 목적과 입구만 보여줍니다. 하위 주제는 1차 메뉴 클릭 후 펼쳐집니다.',
      cards: [
        {
          id: 'research',
          name: 'Research｜연구 핵심',
          position: '이론 엔진',
          intro: 'NexAeon Research는 이론 엔진입니다. AI Education, TAM, VARK, SRL, Learning Engagement 이론을 활용해 교육 문제를 검증 가능한 연구 모델과 증거 경로로 전환합니다.',
          cta: 'Research Roadmap 열기',
        },
        {
          id: 'teaching',
          name: 'Teaching｜교육 설계',
          position: '캠퍼스 문제에서 출발하는 AI 수업 역량',
          intro: 'Teaching은 다문화 학습, AI 질문, 신뢰성 판단, 결과물 전환 문제를 수업 모듈로 정리합니다. 학생은 AI 결과를 과제, 연구, 발표 결과물로 바꾸는 법을 배웁니다.',
          cta: 'Teaching Modules 열기',
        },
        {
          id: 'knowledge',
          name: 'Knowledge Lab｜제2의 뇌',
          position: '자가 성장형 지식 시스템',
          intro: 'Knowledge Lab은 아이디어, 자료, 태그, 자동화, RAG 지식층을 관리합니다. 흩어진 자료를 연구, 수업, 슬라이드, 웹 콘텐츠, Demo/MVP, 협업 제안으로 축적합니다.',
          cta: 'Knowledge Lifecycle 열기',
        },
        {
          id: 'projects',
          name: 'Demo / MVP｜실천 프로토타입',
          position: 'Practice Proof',
          intro: 'Demo / MVP는 연구 질문을 전시, 테스트, 반복 가능한 시스템으로 구현했다는 증거입니다. 일반 포트폴리오가 아니라 연구 적용과 교육 샌드박스입니다.',
          cta: 'Demo Lab 열기',
        },
        {
          id: 'contact',
          name: 'Collaboration｜협업 입구',
          position: '협업 퍼널',
          intro: 'Collaboration은 교수, 대학, 기업, 학생의 요구를 적절한 첫 단계로 분류합니다. 공동 연구, AI 커리큘럼, 교육, 자동화, MVP 공동개발을 연결합니다.',
          cta: 'Collaboration Funnel 열기',
        },
      ],
    },
    research: {
      eyebrow: 'Research Roadmap',
      title: 'Research Roadmap｜연구 지도',
      subtitle: 'AI Education을 중심축으로 이론 모델, 학습 데이터, 연구 시스템, Demo/MVP 실천을 검증 가능한 연구 경로로 연결합니다.',
      roadmapLabel: 'Research Flow',
      theoryLabel: '기반 이론',
      projectsLabel: 'Research Projects｜연구 적용 프로토타입',
      projectsDescription: 'Demo / MVP는 일반 작품 전시가 아니라, 연구 질문을 테스트 가능하고 피드백 수집과 반복 개선이 가능한 실천 증거로 전환한 것입니다.',
      roadmap: [
        {
          title: 'AI Education',
          summary: 'AI가 수업에 들어가는 지점, 경계, 성과 지표를 정의합니다.',
          connects: ['Learning Engagement', 'Satisfaction / Adoption'],
        },
        {
          title: 'Personalized AI Tutoring',
          summary: '학습자 수준, 속도, 과제 목표에 맞춘 개인화 AI 튜터링 전략을 설계합니다.',
          connects: ['VARK', 'SRL'],
        },
        {
          title: 'Learning Engagement / Satisfaction',
          summary: '참여도, 만족도, 채택 의도를 추적해 AI 교육 개입의 실제 효과를 검증합니다.',
          connects: ['Learning Engagement', 'TAM'],
        },
        {
          title: 'AI Management / AI Business Education',
          summary: 'AI 도구를 수업, 기업 교육, 관리 프로세스에 적용해 실전형 교육·운영 모델로 만듭니다.',
          connects: ['TAM', 'Adoption'],
        },
        {
          title: 'NexAeon Research System',
          summary: 'Knowledge Lab, RAG, Demo Lab, Publishing Hub로 연구가 계속 축적되게 합니다.',
          connects: ['Research Workflow', 'Publishing'],
        },
      ],
      theories: [
        { title: 'TAM｜Technology Acceptance Model', summary: '학습자와 조직이 AI 도구를 수용하고 채택하며 지속 사용하는 과정을 설명합니다.' },
        { title: 'VARK｜Learning Styles', summary: '시각, 청각, 읽기/쓰기, 실습 선호에 맞춰 AI Tutor 피드백을 조정합니다.' },
        { title: 'SRL｜Self-Regulated Learning', summary: '목표 설정, 모니터링, 성찰, 자기수정이 AI로 어떻게 지원되는지 살핍니다.' },
        { title: 'Learning Engagement', summary: '참여 깊이, 상호작용 품질, 지속 학습을 추적 가능한 신호로 전환합니다.' },
        { title: 'Satisfaction / Adoption', summary: '학습 만족도, 신뢰, 장기 채택 의도를 측정합니다.' },
      ],
    },
    teaching: {
      eyebrow: 'Teaching Design',
      title: '캠퍼스 문제에서 출발하는 AI 교육 설계',
      subtitle: 'NexAeon의 수업은 도구 시연이 아니라 실제 학생 문제를 가르치고 연습하고 평가할 수 있는 AI 역량으로 전환합니다.',
      painLabel: '캠퍼스 문제',
      solutionLabel: '수업 모듈 × 해결 역량',
      sandboxLabel: 'Teaching Sandbox / Practice Output',
      painPoints: [
        '다문화 학생은 AI에게 어떻게 질문해야 하는지 모릅니다.',
        '학생은 AI 답변의 신뢰성을 판단하는 방법을 모릅니다.',
        '학생은 AI 결과를 과제, 연구, 실무 결과물로 바꾸는 방법을 모릅니다.',
        '배경이 다른 학생들 사이에 AI 도구 활용 역량 차이가 큽니다.',
      ],
      modules: [
        { course: 'Prompt Engineering', solves: '질문을 잘하지 못하는 문제를 해결', output: '구조화된 질문, 과제 경계, 출력 형식, 평가 기준.' },
        { course: 'AI Research Workflow', solves: '문헌, 설문, 데이터 분석, 논문 준비 문제를 해결', output: '연구 질문에서 문헌 요약, 설문 설계, 데이터 정리, 논문 초안까지.' },
        { course: 'Automation Workflow', solves: '반복 행정과 연구 프로세스의 비효율 해결', output: 'n8n / Notion / Airtable 사고를 활용한 반복 가능한 워크플로.' },
        { course: 'AI Presentation / Report Design', solves: '성과 표현과 학술 발표 문제 해결', output: 'AI 결과물을 발표, 보고서, 포스터, 수업 전시로 전환.' },
      ],
      sandbox: 'Demo / MVP는 학생이 AI 교육 도구와 관리 시스템을 이해하는 실습 샌드박스입니다. 학생은 prompt만 배우는 것이 아니라 교육 도구가 어떻게 설계, 테스트, 피드백, 반복 개선되는지 관찰합니다.',
    },
    knowledge: {
      eyebrow: 'Knowledge Lab',
      title: 'Knowledge Lab｜제2의 뇌｜A Self-Growing Knowledge System',
      subtitle: '하나의 자료가 NexAeon에 들어오면 AI 태깅, 자동화 정리, RAG 검색 증강, 프로토타입 실험을 거쳐 연구, 수업, 슬라이드, 웹 콘텐츠, Demo/MVP, 협력 제안으로 축적됩니다.',
      lifecycleLabel: 'Knowledge Lifecycle',
      searchLabel: 'Knowledge Nodes',
      searchPlaceholder: '키워드 검색 (제목, 요약, 분류, 태그)',
      noResults: '조건에 맞는 자료가 없습니다.',
      lifecycle: [
        'Idea Lab',
        'Knowledge Intake',
        'AI Tagging / Automation',
        'RAG Knowledge Layer',
        'MVP / Demo Lab',
        'Research / Teaching / Publishing',
        'Publishing Hub',
      ],
      lifecycleDetails: [
        '연구 아이디어, 수업 관찰, 도구 실험, 협업 요구를 포착합니다.',
        '노트, 문헌, 설문, 인터뷰, 슬라이드, 웹사이트 자료를 수집합니다.',
        'AI가 태그, 분류, 요약, 작업 분류를 돕습니다.',
        '검색, 재조합, 인용이 가능한 지식 증강 레이어를 만듭니다.',
        '지식을 전시와 테스트가 가능한 Demo / MVP로 전환합니다.',
        '논문, 수업, 출판, 교안, 관리 프로세스로 되돌립니다.',
        '글, 웹페이지, 발표자료, 협력 제안서, 공개 자료를 만듭니다.',
      ],
    },
    projects: {
      eyebrow: 'Practice Proof',
      title: 'Demo Lab｜MVP 프로토타입 실험실',
      subtitle: 'NexAeon은 아이디어만 있는 곳이 아니라, 연구 질문을 전시·테스트·반복 가능한 프로토타입 시스템으로 이미 구현하고 있습니다.',
      cardLabels: {
        problem: 'Problem',
        aiLogic: 'AI Logic',
        useCase: 'Use Case',
        status: 'Status',
      },
    },
    contact: {
      eyebrow: 'Collaboration Funnel',
      title: 'Collaboration｜협업 입구',
      description: '협력 대상을 기준으로 연구, 수업, AI 교육, 자동화, MVP 공동개발 요구를 분류해 첫 대화부터 문제에 정확히 맞춥니다.',
      email: 'AJ_Joey@nexaeon.studio',
      mailtoCta: '이메일 보내기',
      copyCta: '이메일 복사',
      copySuccessMessage: '이메일이 클립보드에 복사되었습니다.',
      copyFallbackMessage: '복사에 실패했습니다. 이메일을 수동으로 복사해 주세요.',
      funnelLabel: '협업 분류',
      formLabel: '간단 협업 의향 폼',
      submitLabel: '폼 제출 자리',
      formNote: '이 영역은 Airtable Embed로 교체할 수 있습니다. 현재는 프론트엔드 폼 UI 자리입니다.',
      fields: {
        name: 'Name',
        organization: 'Organization',
        role: 'Role',
        email: 'Email',
        collaborationType: 'Collaboration Type',
        message: 'Message',
      },
      types: [
        'Research Design',
        'AI Training',
        'Automation Workflow',
        'AI Education System',
        'Data / Survey Analysis',
        'Guest Lecture / Workshop',
        'MVP Prototype Co-development',
      ],
      funnels: [
        { title: 'For Professors', items: ['공동 연구', '실험 설계', '설문 및 데이터 분석'] },
        { title: 'For Universities', items: ['AI 커리큘럼 설계', '학생 AI 역량 교육', '교육 혁신 시스템'] },
        { title: 'For Companies', items: ['AI 교육', '자동화 워크플로', 'ESG / HRM / SCM 분석'] },
        { title: 'For Students', items: ['AI 학습 코칭', '연구 훈련', '포트폴리오 구축'] },
      ],
    },
  },
};
